include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - cloudflare_realtime_adapter/**
    - android/**
    - ios/**
    - linux/**
    - web/**
    - windows/**
    - macos/**
