// Generates lib/src/keys/key_tables.g.dart from Flutter's physical key data
// (BSD-3-Clause; see THIRD_PARTY_NOTICES.md).
//
//   dart run tool/gen_key_tables.dart
//
// Reads $FLUTTER_ROOT/dev/tools/gen_keycodes/data/physical_key_data.g.json,
// or the Flutter SDK on PATH.
import 'dart:convert';
import 'dart:io';

void main() {
  final root =
      Platform.environment['FLUTTER_ROOT'] ??
      File((Process.runSync('which', ['flutter']).stdout as String).trim())
          .resolveSymbolicLinksSync()
          .replaceAll(RegExp(r'/bin/flutter$'), '');
  final file = File(
    '$root/dev/tools/gen_keycodes/data/physical_key_data.g.json',
  );
  final data = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final commit =
      (Process.runSync('git', ['-C', root, 'rev-parse', 'HEAD']).stdout
              as String)
          .trim();

  final windows = <int, (int, String)>{};
  final macos = <int, (int, String)>{};
  for (final MapEntry(key: name, value: entry) in data.entries) {
    final codes =
        (entry as Map<String, dynamic>)['scanCodes'] as Map<String, dynamic>;
    final usb = codes['usb'] as int?;
    if (usb == null) continue;
    final win = codes['windows'];
    if (win is int && win != 0) windows[usb] = (win, name);
    final mac = codes['macos'];
    if (mac is int) macos[usb] = (mac, name);
  }

  String table(Map<int, (int, String)> m) {
    final keys = m.keys.toList()..sort();
    return [
      for (final k in keys)
        '  0x${k.toRadixString(16).padLeft(8, '0')}: '
            '0x${m[k]!.$1.toRadixString(16).padLeft(4, '0')}, // ${m[k]!.$2}',
    ].join('\n');
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_key_tables.dart. Do not edit.')
    ..writeln('//')
    ..writeln(
      "// From Flutter's physical_key_data.g.json (BSD-3-Clause), Flutter",
    )
    ..writeln('// commit $commit. See THIRD_PARTY_NOTICES.md.')
    ..writeln()
    ..writeln(
      '/// USB HID usage (`page << 16 | id`) to Windows set-1 scan code.',
    )
    ..writeln(
      '/// Extended keys carry `0xE0` in the high byte (`0xE048` is Up):',
    )
    ..writeln('/// send the low byte with `KEYEVENTF_EXTENDEDKEY`.')
    ..writeln('const Map<int, int> hidToWindowsScanCode = {')
    ..writeln(table(windows))
    ..writeln('};')
    ..writeln()
    ..writeln('/// USB HID usage (`page << 16 | id`) to macOS virtual key code')
    ..writeln("/// (`CGKeyCode`, HIToolbox's `kVK_*`).")
    ..writeln('const Map<int, int> hidToMacKeyCode = {')
    ..writeln(table(macos))
    ..writeln('};');
  File('lib/src/keys/key_tables.g.dart')
    ..createSync(recursive: true)
    ..writeAsStringSync(out.toString());
  stdout.writeln(
    'Wrote ${windows.length} Windows and ${macos.length} macOS keys '
    '(Flutter $commit).',
  );
}
